name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    outputs:
      archive-path: ${{ steps.archive.outputs.path }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'

    - name: Build
      run: |
        xcodebuild -scheme HNSwift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' -derivedDataPath build/derived_data build
      id: archive
      continue-on-error: false

    - name: Save Build Artifact
      if: success()
      run: mkdir -p ${{ github.workspace }}/build && cp -R build/derived_data/Build/Products/Release-iphonesimulator/HNSwift.xcarchive ${{ github.workspace }}/build/

  test:
    runs-on: macos-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'

    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: HNSwift.xcarchive
        path: ${{ github.workspace }}/build/

    - name: Run Tests
      run: |
        xcodebuild -scheme HNSwift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' test -verbose
